site_name: QUICKSILVER

repo_name: BossHobby/QUICKSILVER
repo_url: https://github.com/BossHobby/QUICKSILVER/releases/
edit_uri: 'https://github.com/BossHobby/Docs/tree/master/docs'

nav:
  - Home: index.md
  - Quick Start: Quick-Start-Guide.md
  - Configuring Quicksilver: Configuring-Quicksilver.md
  - Features: Features.md
  - Troubleshooting: Troubleshooting.md
  - About:
      - About/Development.md
      - About/Contributing.md

theme:
  name: material
  logo: assets/img/Logo_Clean.svg
  favicon: assets/img/Logo_Clean.png

  font:
    text: Roboto
    code: Roboto Mono

  palette:
    # Palette toggle for dark mode
    - scheme: slate
      primary: quicksilver
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

    # Palette toggle for light mode
    - scheme: default
      primary: quicksilver
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

  include_search_page: false
  search_index_only: true

  language: en
  features:
    - navigation.instant
    - navigation.tracking
    - toc.integrate

extra_css:
  - assets/style/style.css

markdown_extensions:
  - tables
  - attr_list
  - admonition
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
