site_name: QUICKSILVER

repo_name: BossHobby/QUICKSILVER
repo_url: https://github.com/BossHobby/QUICKSILVER/releases/
edit_uri: 'https://github.com/BossHobby/Docs/tree/master/docs'

theme:
  name: material
  logo: assets/img/Logo_Clean.svg
  favicon: assets/img/Logo_Clean.png

  font:
    text: Roboto
    code: Roboto Mono

  palette:

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode    

  include_search_page: false
  search_index_only: true

  language: en
  features:
    - navigation.instant
    - navigation.tracking
    - toc.integrate

extra_css:
  - assets/style/style.css
