site_name: QUICKSILVER
site_url: !ENV [PAGES_SITE_URL, 'https://docs.bosshobby.com/']

repo_name: BossHobby/QUICKSILVER
repo_url: https://github.com/BossHobby/QUICKSILVER/releases/
edit_uri: !ENV [PAGES_EDIT_URI, 'https://github.com/BossHobby/Docs/tree/master/docs']

hooks:
  - script/llms.py

nav:
  - Home: index.md
  - Scope and Reference: Scope-and-Reference.md
  - Quick Start: Quick-Start-Guide.md
  - Upgrading: Upgrading.md
  - Controller Setup: Configuring-Quicksilver.md
  - Rates, PID and Filters: Tuning.md
  - Features: Features.md
  - Receivers and Passthrough: Receivers-and-Passthrough.md
  - Wings and Rovers: Wings-and-Rovers.md
  - Video and OSD: Video-and-OSD.md
  - Navigation: Navigation.md
  - Blackbox and Diagnostics: Blackbox-and-Diagnostics.md
  - Troubleshooting: Troubleshooting.md
  - About:
      - About/Development.md
      - About/Contributing.md

theme:
  name: material
  custom_dir: overrides
  logo: assets/img/Logo_Clean.svg
  favicon: assets/img/Logo_Clean.png

  font: false

  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: quicksilver
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: quicksilver
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

  include_search_page: false
  search_index_only: true

  language: en
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.sections

extra_css:
  - assets/style/style.css

markdown_extensions:
  - toc:
      title: On this page
  - tables
  - attr_list
  - admonition
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
