site_name: QUICKSILVER

repo_name: BossHobby/QUICKSILVER
repo_url: https://github.com/BossHobby/QUICKSILVER/releases/
edit_uri: 'https://github.com/BossHobby/Docs/tree/master/docs'

theme:
  name: material
  logo: assets/img/logo.svg
  favicon: assets/img/favicon.png
  font:
    text: Roboto
    code: Roboto Mono

  palette:
    scheme: default

  include_search_page: false
  search_index_only: true

  language: en
  features:
    - navigation.instant
    - navigation.tracking
